In [ ]:
metal_dict = {
    "Sc": [3, 1.36, 6.62],
    "Ti": [4, 1.54, 10.39], 
    "V": [5, 1.63, 15.34], 
    "Cr": [6, 1.66, 21.69], 
    "Mn": [7, 1.55, 31.61], 
    "Fe": [8, 1.83, 34.97], 
    "Co": [9, 1.88, 43.09], 
    "Ni": [10, 1.91, 52.36], 
    "Cu": [11, 1.90, 63.68], 
    "Zn": [12, 1.65, 87.27], 
    "Y": [3, 1.22, 7.38], 
    "Zr": [4, 1.33, 12.03], 
    "Nb": [5, 1.60, 15.63], 
    "Mo": [6, 1.16, 31.03], 
    "Tc": [7, 1.90, 25.79], 
    "Ru": [8, 2.20, 29.09], 
    "Rh": [9, 2.28, 35.53], 
    "Pd": [10, 2.20, 45.45], 
    "Ag": [11, 1.93, 87.10],
    "Cd": [12, 1.69, 85.21], 
    "La": [3, 1.10, 8.18], 
    "Hf": [4, 1.30, 12.31], 
    "Ta": [5, 1.50, 16.67], 
    "W": [6, 2.36, 15.25], 
    "Re": [7, 1.90, 25.79], 
    "Os": [8, 2.20, 29.09],
    "Ir": [9, 2.20, 36.82], 
    "Pt": [10, 2.28, 43.86],
    "Au": [11, 2.54, 75.92], 
    "Hg": [12, 2.00, 72],
}

coord_num_dict = {
    "2AD@211": 1.667, # 
    "1AD@111": 2.500, 
    "2AD@111": 2.917, 
    "1AD@100": 3.000, 
    "3AD@111": 3.500, 
    "2AD@100": 3.583, 
    "4AD@100": 4.417, 
    "211 KSE (CN=6)": 4.667, 
    "532 T": 4.750, 
    "211 SE": 5.500, 
    "553 SE": 5.500, 
    "711 SE": 5.500, 
    "110 SE": 5.833, 
    "211 KSE (CN=8)": 6.417, 
    "100 T (hollow)": 6.615, 
    "100 T": 6.667, 
    "111 T (FCC-hollow)": 6.955, 
    "111 T": 7.500, 
    "cavity 111": 8.000,
}